#!/bin/bash
###PBS -l nodes=10:ppn=60
#PBS -l nodes=1:ppn=24
#PBS -l pmem=2GB
#PBS -l walltime=1:00:00
#PBS -q hive-interact
#PBS -N Al_scaling
#PBS -o stdout
#PBS -e stderr
cd $PBS_O_WORKDIR

#module load anaconda3/4.2.0;source activate atm
ulimit -s unlimited

export MV2_ENABLE_AFFINITY=1
export MV2_CPU_BINDING_POLICY=bunch
#export MALLOC_MMAP_MAX_=0 
#export M_TRIM_THRESHOLD_=-1

mpirun -np $PBS_NP ../../../lib/sparc -name sprc-calc > sprc-calc.log
